export const BOTS_PROVIDER = 'BOTS_PROVIDER';
export const BOTS_STYLE_PROVIDER = 'BOTS_STYLE_PROVIDER';
export const BOTS_SETTING_PROVIDER = 'BOTS_SETTING_PROVIDER';
export const BOTS_FLOW_PROVIDER = 'BOTS_FLOW_PROVIDER';
export const BOTS_NODE_PROVIDER = 'BOTS_NODE_PROVIDER';
