export const TEMPLATE_SESSION_PROVIDER = 'TEMPLATE_SESSION_MODEL';
export const TEMPLATE_SUBMISSION_PROVIDER = 'TEMPLATE_SUBMISSION_MODEL';

export const DEFAULT_SESSION_EXPIRY_MINUTES = 30;
export const DEFAULT_TIMEOUT_MINUTES = 30;
