

upstream api{
    server backend:3001;
    keepalive 64;
}

upstream public{
    server public:3002;
    keepalive 64;
}

upstream admin{
    server admin:3003;
    keepalive 64;
}


upstream healthcheck{
    server health:3004;
    keepalive 64;
}


server {
    listen 80;
    server_name localhost;

  

   location /api {

    
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://api;
   }

    location /public {
        rewrite ^/public/(.*)$ /$1 break;
        proxy_pass http://public;
    }
    location /healthcheck {
        rewrite ^/healthcheck(.*)$ /$1 break;
        proxy_pass http://healthcheck;
    }
}








server {

    listen 1443;
    server_name localhost;
   location /{
    proxy_pass http://admin;
   }

}
