import React from 'react';
import PageShell from '../components/PageShell';
import BookACallSection from '../components/BookACallSection';
import Icon from '../components/Icon';
import { featureBySlug, features } from '../content/features';

/**
 * One implementation serving all five feature detail routes, keyed by slug.
 *
 * The "other features" strip at the bottom is generated by excluding the current
 * slug, so adding a sixth feature wires itself into the cross-links with no edit
 * here.
 */
interface FeaturePageProps {
  slug: string;
}

const FeaturePage: React.FC<FeaturePageProps> = ({ slug }) => {
  const feature = featureBySlug(slug);

  if (!feature) {
    return (
      <PageShell currentPath={`/features/${slug}`}>
        <section className="jc-section jc-page-head">
          <div className="jc-container jc-container--narrow">
            <h1>Feature not found</h1>
            <p className="jc-lead">
              We could not find that page. Head back to the homepage to see what
              the platform covers.
            </p>
            <a className="jc-btn jc-btn--primary" href="/">
              Back to home
            </a>
          </div>
        </section>
      </PageShell>
    );
  }

  const others = features.filter((f) => f.slug !== feature.slug);

  return (
    <PageShell currentPath={`/features/${feature.slug}`}>
      <section className="jc-section jc-page-head" aria-labelledby="jc-feature-heading">
        <div className="jc-container">
          <nav className="jc-breadcrumb" aria-label="Breadcrumb">
            <a href="/">Home</a>
            <span aria-hidden="true"> / </span>
            <span aria-current="page">{feature.cardTitle}</span>
          </nav>

          <div className="jc-container--narrow jc-feature-head">
            <span className="jc-icon-tile jc-feature-head__icon">
              <Icon name={feature.icon} className="jc-icon jc-icon--lg" />
            </span>
            <h1 id="jc-feature-heading">{feature.title}</h1>
            <p className="jc-lead">{feature.intro}</p>
          </div>
        </div>
      </section>

      <section
        className="jc-section jc-section--sunken"
        aria-labelledby="jc-feature-detail"
      >
        <div className="jc-container jc-container--narrow">
          <h2 id="jc-feature-detail" className="jc-sr-only">
            How it works
          </h2>
          <div className="jc-prose">
            {feature.sections.map((section) => (
              <article className="jc-prose__block" key={section.heading}>
                <h3>{section.heading}</h3>
                <p>{section.body}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="jc-section" aria-labelledby="jc-feature-others">
        <div className="jc-container">
          <div className="jc-section-head">
            <span className="jc-eyebrow">Also in JarCube</span>
            <h2 id="jc-feature-others">The rest of the platform</h2>
          </div>

          <div className="jc-grid jc-grid--4">
            {others.map((other) => (
              <a
                key={other.slug}
                className="jc-card jc-card--interactive jc-feature-card"
                href={`/features/${other.slug}`}
              >
                <span className="jc-icon-tile">
                  <Icon name={other.icon} className="jc-icon jc-icon--lg" />
                </span>
                <h3 className="jc-feature-card__title">{other.cardTitle}</h3>
                <p className="jc-feature-card__body">{other.cardSummary}</p>
              </a>
            ))}
          </div>
        </div>
      </section>

      <BookACallSection />
    </PageShell>
  );
};

export default FeaturePage;
